services:
  - type: web
    name: mudae-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py & python -m http.server 10000
    envVars:
      - key: DISCORD_TOKEN
        sync: false
